#!/usr/bin/env bash
# install and setup nginx
CONFIG_FILE="/etc/nginx/sites-available/default"
# install nginx
sudo apt-get -y update
sudo apt-get -y install nginx

# update index.html file
echo "Hello World!" > /usr/share/nginx/html/index.html

# update config file to redirect
printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root   /usr/share/nginx/html;
    index  index.html index.htm;
    location /redirect_me {
        return 301 http://google.com/;
    }
}" > $CONFIG_FILE

# start nginx after reloading config
service nginx start
