#!/usr/bin/env bash
# Bash script to install and configure HAproxy on your lb-01 server

sudo apt-get -y install software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-1.8
sudo apt-get -y update
sudo apt-get -y install haproxy=1.8\*

echo "
frontend http
 bind *:80
 stats uri /haproxy?stats
 default_backend web-backend
backend web-backend
balance roundrobin
server 1135-web-01 54.174.44.47  check
server 1135-web-02 52.201.219.255 check" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
