#!/usr/bin/env bash
#Bash script that displays a message when it is terminated
#when receiving a SIGTERM signal

trap 'echo "I am invincible!!!"' SIGTERM
while true
do
	echo "To infinity and beyond"
	sleep 2
done
