#!/usr/bin/env bash
# FizzBuzz - print 1 to 100, "Fizz" for multiples of 3,
# "Buzz" for multiples of 5, and "FizzBuzz" for multiples of 3 and 5

n=0
while [ $((n++)) -lt 100 ]; do
	if [ $((n % 15)) -eq 0 ]; then
		echo "FizzBuzz"
	elif [ $((n % 5)) -eq 0 ]; then
		echo "Buzz"
	elif [ $((n % 3)) -eq 0 ]; then
		echo "Fizz"
	else
		echo "$n"
	fi
done
