#!/usr/bin/env bash
# Display "Best School" 10x, "bad luck" the 4th, "good luck" the 8th

n=1
while [ $n -le 10 ]
do
    if [ $n -eq 4 ]; then
	echo "bad luck"
    elif [ $n -eq 8 ]; then
	echo "good luck"
    else
	echo "Best School"
    fi
    (( n++ ))
done
