#!/usr/bin/env bash
# Runs nginx as the user nginx and listening on port 8080
sed -i "s/80/8080/" /etc/nginx/sites-enabled/default
chmod 204 /etc/nginx/nginx.conf
sed -i '1iuser nginx;' /etc/nginx/nginx.conf
pkill -f apache2
sudo -u nginx service nginx start
