#!/usr/bin/env bash
# Runs nginx as the user nginx and listening on port 8080 but shorter
chmod 204 /etc/nginx/nginx.conf
sed -i "s/80/8080/" /etc/nginx/sites-available/default
pkill -f apache2
sudo -u nginx service nginx start
